dist: xenial
language: python

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8

addons:
  postgresql: 10

install:
  - python -m pip install --upgrade pip
  - pip install tox-travis

before_script:
  - psql -U postgres -c "create user test with superuser password 'test';"

script:
  - tox
